config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  root to: 'pages#home'
  resources :cocktails do
    collection do
      get 'search', to: 'cocktails#pour'
    end

    member do
      resources :doses, only: %i[new create]
      resources :reviews, only: %i[new create]
    end
  end
  delete 'doses/:id', to: 'doses#delete', as: 'delete_doses'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/cocktail.rb
class Cocktail < ApplicationRecord
  has_many :doses, dependent: :destroy
  has_many :ingredients, through: :doses
  has_many :reviews
  has_one_attached :photo

  validates :name, presence: true, uniqueness: true
  validates :photo, presence: true
end

app/models/dose.rb
class Dose < ApplicationRecord
  belongs_to :cocktail
  belongs_to :ingredient

  validates :description, :cocktail_id, presence: true
  validates :cocktail_id, uniqueness: { scope: :ingredient }
end

app/models/ingredient.rb
class Ingredient < ApplicationRecord
  has_many :doses
  has_many :cocktails, through: :doses

  validates :name, presence: true, uniqueness: true
end

app/models/review.rb
class Review < ApplicationRecord
  belongs_to :cocktail

  validates :content, :rating, :name, presence: true
  validates :rating, inclusion: 0..5
  validates :rating, numericality: { only_integer: true }
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  has_one_attached :avatar
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :authenticate_user!

  def configure_permitted_parameters
    devise_parameter_sanitizer.permit(:sign_up, keys: [:first_name, :last_name])
    devise_parameter_sanitizer.permit(:account_update, keys: [:first_name, :last_name])
  end
end

app/controllers/cocktails_controller.rb
class CocktailsController < ApplicationController
  skip_before_action :authenticate_user!, only: %i[index show]
  before_action :find_cocktail, only: %i[show edit update destroy]

  def index
    @cocktails = Cocktail.all
  end

  def show
    @doses = Dose.where('cocktail_id = ?', params[:id])
  end

  def new
    @cocktail = Cocktail.new
  end

  def create
    @cocktail = Cocktail.new(cocktail_params)
    if @cocktail.save
      redirect_to new_dose_path(@cocktail)
    else
      render :new
    end
  end

  def edit; end

  def update
    if @cocktail.update(cocktail_params)
      redirect_to cocktail_path(@cocktail)
    else
      render :new
    end
  end

  def destroy
    @cocktail.destroy
    redirect_to cocktails_path
  end

  def pour
    @query1 = params[:query].capitalize
    @query2 = params[:query].downcase
    @cocktails = Cocktail.where('name LIKE ? OR name LIKE ?', "%#{@query1}%", "%#{@query2}%")
  end

  private

  def find_cocktail
    @cocktail = Cocktail.find(params[:id])
  end

  def cocktail_params
    params.require(:cocktail).permit(:name, :photo)
  end
end

app/controllers/doses_controller.rb
class DosesController < ApplicationController
  def new
    @cocktail = Cocktail.find(params[:id])
    @dose = Dose.new
    @ingredients = Ingredient.all
    @current_dose = Dose.where('cocktail_id = ?', params[:id])
  end

  def create
    @cocktail = Cocktail.find(params[:id])
    @dose = Dose.new(dose_params)
    @dose.save
    redirect_to new_dose_path(@cocktail)
  end

  def delete
    @dose = Dose.find(params[:id])
    @cocktail = Cocktail.find(@dose.cocktail_id)
    @dose.destroy
    redirect_to cocktail_path(@cocktail)
  end

  private

  def dose_params
    params.require(:dose).permit(:cocktail_id, :description, :ingredient_id)
  end
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  skip_before_action :authenticate_user!, only: :home
  
  def home
    @cocktails = Cocktail.all
    @cocktails_sample = [@cocktails.sample, @cocktails.sample, @cocktails.sample]
  end
end

app/controllers/reviews_controller.rb
class ReviewsController < ApplicationController
  skip_before_action :authenticate_user!, only: :home
  before_action :find_cocktail

  def new
    @review = Review.new
  end

  def create
    @review = Review.new(review_params)
    @review.cocktail = @cocktail
    if @review.save
      redirect_to cocktail_path(@cocktail)
    else
      render :new
    end
  end

  private

  def find_cocktail
    @cocktail = Cocktail.find(params[:id])
  end

  def review_params
    params.require(:review).permit(:content, :rating, :name)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/cocktails_helper.rb
module CocktailsHelper
end

app/helpers/doses_helper.rb
module DosesHelper
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/helpers/reviews_helper.rb
module ReviewsHelper
end

app/views/cocktails/edit.html.erb
<div class="container bigger-container">
  <div class="d-flex justify-content-center align-items-center my-4">
    <h1>Update a cocktail</h1>
  </div>

  <%= render partial: "components/form" %>
</div>

app/views/cocktails/index.html.erb
<div class="container bigger-container">
  <div class="d-flex justify-content-center align-items-center my-4">
    <h1>Cocktails</h1>
  </div>

  <div class="container">
    <div class="row">
        <% @cocktails.each do |tail| %>
          <div class="col-lg-4 col-md-6 col-12 my-4">
            <%= link_to cocktail_path(tail) do %>
              <div class="card-category" style="background-image: linear-gradient(rgba(0,0,0,0.5), rgba(0,0,0,0.5)), url('<%= cl_image_path tail.photo.key %>')">
                <%= tail.name %>
              </div>
            <% end %>
          </div>
        <% end %>
    </div>
  </div>
</div>

app/views/cocktails/new.html.erb
<div class="container bigger-container">
  <div class="d-flex justify-content-center align-items-center my-4">
    <h1>Create a new cocktail</h1>
  </div>

  <div class="form-div w-50">
    <%= simple_form_for(@cocktail) do |f| %>
    <%= f.input :name, input_html: { placeholder: "Cocktail Name" }, label: false %>
    <%= f.input :photo, as: :file, label: false %>
    <%= f.button :submit, class: "btn-success w-100" %>
    <% end %>
  </div>
</div>

app/views/cocktails/pour.html.erb
<div class="container bigger-container">
  <div class="d-flex justify-content-center align-items-center my-4">
    <h1>Update a cocktail</h1>
  </div>

  <div class="row form-div">
    <% @cocktails.each do |tail| %>
      <div class="col-12">
        <%= link_to cocktail_path(tail) do %>
            <div class="card-product my-2">
              <img src='<%= cl_image_path tail.photo.key %>' />
              <div class="card-product-infos">
                <h2><%= tail.name %></h2>
              </div>
            </div>
        <% end %>
      </div>
    <% end %>
  </div>
</div>

app/views/cocktails/show.html.erb
<div class="banner banner-tail" style="background-image: linear-gradient(rgba(0,0,0,0.6),rgba(0,0,0,0.6)), url('<%= cl_image_path @cocktail.photo.key %>'); object-fit: cover;">
  <div class="container updelicon">
    <div>
      <h1><%= @cocktail.name %></h1>
    </div>
    <div class="updelicons">
      <%= link_to edit_cocktail_path(@cocktail), class: "updelicon" do %>
        <i class="fas fa-pen fa-2x"></i>
      <% end %>
      <%= link_to cocktail_path(@cocktail), class: "updelicon", method: :delete, data: { confirm: 'Are you sure?' } do %>
        <i class="fas fa-trash fa-2x"></i>
      <% end %>
    </div>
  </div>
</div>

<div class="row">
    <div class="col-12 col-lg-6">
      <div class="ingredients-show-div m-4 p-4 rounded shadow-sm">
        <div>
          <h1>Ingredients</h1>
          <div class="py-2">
            <% @doses.each do |dose| %>
              <p><%= dose.description %> <%= dose.ingredient.name %> <%= link_to "(Delete)", delete_doses_path(dose), class: "deletoshi", method: :delete, data: { confirm: 'Are you sure?' } %></p>
            <% end %>
          </div>
        </div>
      </div>
    </div>
    <div class="col-12 col-lg-6">
      <div class="ingredients-show-div m-4 p-4 rounded shadow-sm">
        <div>
          <h1>Reviews</h1>
          <div class="py-2">
            <% @cocktail.reviews.each do |rev| %>
              <p>
                <strong class="moroonoshi"><%= rev.name %></strong> -
                <%= rev.content %>
                <% rev.rating.times do %>
                  ⭐
                <% end %>
              </p>
            <% end %>
          </div>
        </div>
        <div class="d-flex justify-content-center">
          <%= link_to "Add a Review", new_review_path(@cocktail), class: "btn btn-success" %>
        </div>
      </div>
    </div>
  </div>
</div>

app/views/doses/new.html.erb
<div class="banner banner-tail"
  style="background-image: linear-gradient(rgba(0,0,0,0.6),rgba(0,0,0,0.6)), url('<%= cl_image_path @cocktail.photo.key %>');object-fit: cover;">
  <div class="container">
    <h1><%= @cocktail.name %></h1>
  </div>
</div>

<div class="container">
  <div class="d-flex justify-content-center align-items-center my-4">
    <h1>Add ingredients to <%= @cocktail.name %></h1>
  </div>

  <div class="row">
    <div class="col-12 col-lg-6">
      <div class="ingredioshi m-2 p-4 border rounded shadow-sm">
        <div>
          <h3>Ingredients</h3>
          <div class="py-2">
            <% @current_dose.each do |dose| %>
            <p><%= dose.description %> <%= dose.ingredient.name %></p>
            <% end %>
          </div>
        </div>
      </div>
    </div>
    <div class="col-12 col-lg-6">
      <div class="m-2 p-4 border rounded shadow-sm">
        <div class="form-div-ingredients w-50">
          <%= simple_form_for(@dose) do |f| %>
          <%= f.hidden_field :cocktail_id, value: @cocktail.id %>
          <%= f.input :description, input_html: { placeholder: "Description" }, label: false %>
          <%= f.association :ingredient, input_html: { class: 'select2' }, label: false  %>
          <%# prompt: "Category" , collection: @ingredients.sort%> 
          <%= f.button :submit, 'Add Ingredient', class: "btn-success w-100" %>
          <% end %>
        </div>
      </div>
    </div>
  </div>
  <div class="p-3">
    <% if !@current_dose.empty? %>
    <%= link_to "Finialize Creation", cocktails_path, class: "btn btn-outline-success w-100" %>
    <% end %>
  </div>
</div>

<%# 
<select class="select2" name="country">
  <option value="AL">Alabama</option>
  <option value="WY">Wyoming</option>
</select> %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>

<head>
  <title>Spicybrew</title>
  <meta name="viewport" content="width=device-width, initial-scale=1">
  <meta http-equiv="X-UA-Compatible" content="IE=edge,chrome=1"> <%= csrf_meta_tags %>
  <link rel="icon" type="image/png" href="https://res.cloudinary.com/dc1w9349i/image/upload/v1613778969/marticon_hagbjw.jpg"/>
  <%= csp_meta_tag %>
  <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
  <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload', defer: true %>
  <%= javascript_include_tag "https://cdn.jsdelivr.net/npm/@popperjs/core@2.6.0/dist/umd/popper.min.js", defer: true %>
  <%= javascript_include_tag "https://cdn.jsdelivr.net/npm/bootstrap@5.0.0-beta2/dist/js/bootstrap.min.js", defer: true %>
</head>

<body>
  <%= render partial: "components/navbar" %>
  <%= yield %>
  <%= render partial: "components/footer" %>
  <%= render partial: "shared/alerts" %>
</body>

</html>

app/views/pages/home.html.erb
<div class="banner banner-home" style="background-image: linear-gradient(rgba(0,0,0,0.6),rgba(0,0,0,0.6)), url(https://res.cloudinary.com/dc1w9349i/image/upload/v1613738951/mister-cocktail/bartender_pfyann.jpg);">
  <div class="container">
    <h1>Welcome to Spicybrew</h1>
    <p>Change your life and learn to make some of the nicest cocktails out there.</p>
    <a class="btn btn-outline-primary w-25" href="/cocktails">Cocktail List</a>
  </div>
</div>

<div class="d-flex justify-content-center align-items-center my-4">
  <h1>Featured Cocktails</h1>
</div>

<div class="container">
  <div class="row">
    <% @cocktails_sample.each do |tail| %>
      <div class="col-lg-4 col-md-6 col-12 my-4">
        <%= link_to cocktail_path(tail) do %>
          <div class="card-category" style="background-image: linear-gradient(rgba(0,0,0,0.5), rgba(0,0,0,0.5)), url('<%= cl_image_path tail.photo.key %>')">
            <%= tail.name %>
          </div>
        <% end %>
      </div>
    <% end %>
  </div>
</div>

app/views/reviews/new.html.erb
<div class="container bigger-container">
  <div class="d-flex justify-content-center align-items-center my-4">
    <h1>Add a Review for <%= @cocktail.name %></h1>
  </div>
  <div class="form-div w-50">
    <%= simple_form_for [@restaurant, @review] do |f| %>
      <%= f.input :name, input_html: { placeholder: 'Your name' }, label: false %>
      <%= f.input :content, input_html: { placeholder: 'Content' }, label: false %>
      <%= f.input :rating, collection: [5, 4, 3, 2, 1, 0], label: false, prompt: "Rating" %>
      <%= f.button :submit, class: "btn-success w-100" %>
    <% end %>
  </div>
</div>

app/views/shared/_alerts.html.erb
<% if notice %>
  <div class="alert alert-info alert-dismissible" role="alert">
    <button type="button" class="close" data-dismiss="alert" aria-label="Close"><span aria-hidden="true">&times;</span></button>
    <%= notice %>
  </div>
<% end %>
<% if alert %>
  <div class="alert alert-warning alert-dismissible" role="alert">
    <button type="button" class="close" data-dismiss="alert" aria-label="Close"><span aria-hidden="true">&times;</span></button>
    <%= alert %>
  </div>
<% end %>